[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-155
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  shard-two/0 [idle] active: Primary
  config-server/0 [idle] active: 
  config-server/1 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/1 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] blocked: Shard requires TLS to be enabled.
  shard-two/0 [idle] active: Primary
  config-server/0 [executing] active: 
  config-server/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/1 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/2 [idle] blocked: Shard requires TLS to be enabled.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard requires TLS to be enabled.
  shard-one/1 [executing] maintenance: enabling TLS
  shard-one/2 [executing] blocked: Shard requires TLS to be enabled.
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/1 [idle] active: 
  shard-one/2 [executing] blocked: Shard requires TLS to be enabled.
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] blocked: Shard requires TLS to be enabled.
  shard-one/1 [idle] active: 
  shard-one/2 [executing] blocked: Shard requires TLS to be enabled.
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] waiting: waiting to reconfigure replica set
  shard-one/1 [idle] active: 
  shard-one/2 [executing] maintenance: enabling TLS
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] waiting: waiting to reconfigure replica set
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] blocked: shards shard-one are unreachable.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] active: 
  config-server/0 [idle] active: 
  config-server/1 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] active: 
  shard-one/1 [executing] maintenance: enabling TLS
  shard-one/2 [executing] maintenance: enabling TLS
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  shard-two/0 [idle] active: Primary
  config-server/0 [executing] active: 
  config-server/1 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] active: 
  shard-one/1 [idle] active: 
  shard-one/2 [idle] active: 
  shard-two/0 [idle] active: Primary
  config-server/0 [idle] active: 
  config-server/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/1 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/2 [idle] blocked: Shard has TLS enabled, but config-server does not.
  shard-two/0 [idle] blocked: Shard has TLS enabled, but config-server does not.
  config-server/0 [executing] active: 
  config-server/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  shard-one/0 [executing] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/1 [executing] blocked: Shard has TLS enabled, but config-server does not.
  shard-one/2 [executing] blocked: Shard has TLS enabled, but config-server does not.
  shard-two/0 [executing] blocked: Shard has TLS enabled, but config-server does not.
  config-server/0 [executing] maintenance: enabling TLS
  config-server/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  config-server/0 [idle] waiting: waiting to reconfigure replica set
  config-server/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  02:16:50Z

App                                Version  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
config-server                               active       2  mongodb-k8s                                3  10.152.183.64   no       
self-signed-certificates                    active       1  self-signed-certificates  latest/stable  155  10.152.183.146  no       
self-signed-certificates-separate           active       1  self-signed-certificates  latest/stable  155  10.152.183.115  no       
shard-one                                   waiting      3  mongodb-k8s                                4  10.152.183.41   no       installing agent
shard-two                                   waiting      1  mongodb-k8s                                5  10.152.183.186  no       installing agent

Unit                                  Workload  Agent  Address       Ports  Message
config-server/0*                      active    idle   10.1.174.99          Primary
config-server/1                       active    idle   10.1.174.100         
self-signed-certificates-separate/0*  active    idle   10.1.174.113         
self-signed-certificates/0*           active    idle   10.1.174.90          
shard-one/0*                          blocked   idle   10.1.174.106         Shard CA and Config-Server CA don't match.
shard-one/1                           blocked   idle   10.1.174.107         Shard CA and Config-Server CA don't match.
shard-one/2                           blocked   idle   10.1.174.109         Shard CA and Config-Server CA don't match.
shard-two/0*                          active    idle   10.1.174.112         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-config-server-0: 01:37:11 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard shard-one to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1729474630, 1), 'signature': {'hash': b'\\xf3\\xbd\\xfc=\\xd5\\xd4^:\\x7f\\x1d\\xb3cG]\\xcbfk\\x8dt\\x86', 'keyId': 7428036425355886618}}, 'operationTime': Timestamp(1729474630, 1)}")
unit-config-server-0: 01:37:11 ERROR unit.config-server/0.juju-log config-server:6: shard-one shard does not have the same auth as the config server.
unit-config-server-0: 01:37:28 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729474647, 1), \'signature\': {\'hash\': b\'vV\\x15i\\x89\\xbf\\xc4\\xbf\\xae\\xe0\\xb1o\\xee+\\xc9)\\x90?\\x04/\', \'keyId\': 7428036425355886618}}, \'operationTime\': Timestamp(1729474647, 1)}')
unit-config-server-0: 01:37:28 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard-one to cluster
unit-config-server-0: 01:37:28 ERROR unit.config-server/0.juju-log config-server:6: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729474647, 1), \'signature\': {\'hash\': b\'vV\\x15i\\x89\\xbf\\xc4\\xbf\\xae\\xe0\\xb1o\\xee+\\xc9)\\x90?\\x04/\', \'keyId\': 7428036425355886618}}, \'operationTime\': Timestamp(1729474647, 1)}')
unit-config-server-0: 01:37:43 ERROR unit.config-server/0.juju-log config-server:7: Failed to add shard shard-two to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1729474663, 1), 'signature': {'hash': b'\\x89\\xfe\\x98\\xdal\\x95w\\x81qU\\x0e\\xc4Et\\x80\\xd9\\xb12c\\xe2', 'keyId': 7428036425355886618}}, 'operationTime': Timestamp(1729474663, 1)}")
unit-config-server-0: 01:37:43 ERROR unit.config-server/0.juju-log config-server:7: shard-two shard does not have the same auth as the config server.
unit-shard-two-0: 01:40:24 ERROR unit.shard-two/0.juju-log certificates:9: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 01:40:25 ERROR unit.shard-one/0.juju-log certificates:8: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-2: 01:40:25 ERROR unit.shard-one/2.juju-log certificates:8: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 01:40:25 ERROR unit.config-server/1.juju-log certificates:10: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-1: 01:40:25 ERROR unit.shard-one/1.juju-log certificates:8: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-two-0: 01:40:25 ERROR unit.shard-two/0.juju-log certificates:9: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-0: 01:40:25 ERROR unit.shard-one/0.juju-log certificates:8: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-2: 01:40:25 ERROR unit.shard-one/2.juju-log certificates:8: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 01:40:25 ERROR unit.config-server/1.juju-log certificates:10: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-1: 01:40:25 ERROR unit.shard-one/1.juju-log certificates:8: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:40:32 ERROR unit.config-server/0.juju-log certificates:10: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-0: 01:40:33 ERROR unit.config-server/0.juju-log certificates:10: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 01:40:44 ERROR unit.config-server/1.juju-log certificates:10: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 01:40:44 ERROR unit.config-server/1.juju-log certificates:10: This operation (update_relation_data()) can only be performed by the leader unit
unit-shard-one-2: 01:40:53 ERROR unit.shard-one/2.juju-log certificates:8: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/pool.py", line 538, in command
    return command(
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/network.py", line 208, in command
    reply = receive_message(conn, request_id)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/network.py", line 320, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/network.py", line 404, in _receive_data_on_socket
    raise OSError("connection closed")
OSError: connection closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1866, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 1924, in _on_relation_changed
    self.on.certificate_available.emit(
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/mongodb_tls.py", line 249, in _on_certificate_available
    self.charm.restart_charm_services()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1474, in restart_charm_services
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1618, in _connect_pbm_agent
    self.has_config_server() and self.shard._is_added_to_cluster()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 1097, in _is_added_to_cluster
    cluster_shards = self.get_shard_members()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 1146, in get_shard_members
    return mongo.get_shard_members()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/mongos.py", line 92, in get_shard_members
    shard_list = self.client.admin.command("listShards")
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/database.py", line 930, in command
    return self._command(
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/database.py", line 770, in _command
    return conn.command(
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/helpers.py", line 45, in inner
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/pool.py", line 566, in command
    self._raise_connection_failure(error)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/pool.py", line 763, in _raise_connection_failure
    _raise_connection_failure(self.address, error, timeout_details=details)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/pymongo/synchronous/pool.py", line 208, in _raise_connection_failure
    raise AutoReconnect(msg) from error
pymongo.errors.AutoReconnect: config-server-0.config-server-endpoints:27018: connection closed (configured timeouts: connectTimeoutMS: 2000.0ms)
unit-shard-one-2: 01:40:54 ERROR juju.worker.uniter.operation hook "certificates-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-config-server-1: 01:40:59 ERROR unit.config-server/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 01:40:59 ERROR unit.config-server/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-shard-one-0: 01:41:40 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 6715b153237ba2970076f301, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0008899729999711781>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0006775460000199018>]>
unit-shard-one-0: 01:41:45 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 6715b1574adfe3dd8b949d83, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.002167835000022933>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0016418370000792493>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0037883449999753793>]>
unit-shard-one-0: 01:41:49 ERROR unit.shard-one/0.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 6715b15b41f97e9fefe16cd4, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0013837000000194166>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0023944970000684407>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: RSSecondary, rtt: 0.0014554730000782001>]>
unit-shard-one-0: 01:43:07 ERROR unit.shard-one/0.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:43:07 ERROR unit.shard-one/0.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:43:10 ERROR unit.shard-one/1.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:43:10 ERROR unit.shard-one/1.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-one-2: 01:43:30 ERROR unit.shard-one/2.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-one-2: 01:43:30 ERROR unit.shard-one/2.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:43:33 ERROR unit.shard-one/1.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:43:33 ERROR unit.shard-one/1.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:43:36 ERROR unit.shard-one/0.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:43:36 ERROR unit.shard-one/0.juju-log certificates:8: An unknown certificate is available -- ignoring.
unit-shard-two-0: 01:45:33 ERROR unit.shard-two/0.juju-log certificates:9: An unknown certificate is available -- ignoring.
unit-shard-two-0: 01:45:33 ERROR unit.shard-two/0.juju-log certificates:9: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:47:19 ERROR unit.config-server/0.juju-log certificates:10: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:47:19 ERROR unit.config-server/0.juju-log certificates:10: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:47:22 ERROR unit.config-server/1.juju-log certificates:10: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:47:22 ERROR unit.config-server/1.juju-log certificates:10: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:47:22 ERROR unit.config-server/1.juju-log certificates:10: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 01:47:22 ERROR unit.config-server/1.juju-log certificates:10: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-0: 01:47:40 ERROR unit.config-server/0.juju-log certificates:10: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:47:40 ERROR unit.config-server/0.juju-log certificates:10: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:47:43 ERROR unit.config-server/1.juju-log certificates:10: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:47:44 ERROR unit.config-server/1.juju-log certificates:10: An unknown certificate is available -- ignoring.
unit-config-server-1: 01:47:51 ERROR unit.config-server/1.juju-log certificates:10: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 01:47:51 ERROR unit.config-server/1.juju-log certificates:10: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 01:51:59 ERROR unit.config-server/1.juju-log certificates:10: This operation (delete_relation_data()) can only be performed by the leader unit
unit-config-server-1: 01:51:59 ERROR unit.config-server/1.juju-log certificates:10: This operation (delete_relation_data()) can only be performed by the leader unit
unit-self-signed-certificates-0: 01:52:04 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6fada3fd-9be7-47de-8804-435d7dd4dd03:r#9#shard-two": settings 6fada3fd-9be7-47de-8804-435d7dd4dd03:r#9#shard-two not found (not found)
unit-shard-two-0: 01:52:09 ERROR unit.shard-two/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/pool.py", line 538, in command
    return command(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/network.py", line 208, in command
    reply = receive_message(conn, request_id)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/network.py", line 320, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/network.py", line 404, in _receive_data_on_socket
    raise OSError("connection closed")
OSError: connection closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1866, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1092, in _on_secret_changed
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1618, in _connect_pbm_agent
    self.has_config_server() and self.shard._is_added_to_cluster()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 1097, in _is_added_to_cluster
    cluster_shards = self.get_shard_members()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 1146, in get_shard_members
    return mongo.get_shard_members()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/mongos.py", line 92, in get_shard_members
    shard_list = self.client.admin.command("listShards")
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/database.py", line 930, in command
    return self._command(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/database.py", line 770, in _command
    return conn.command(
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/helpers.py", line 45, in inner
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/pool.py", line 566, in command
    self._raise_connection_failure(error)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/pool.py", line 763, in _raise_connection_failure
    _raise_connection_failure(self.address, error, timeout_details=details)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/pymongo/synchronous/pool.py", line 208, in _raise_connection_failure
    raise AutoReconnect(msg) from error
pymongo.errors.AutoReconnect: config-server-1.config-server-endpoints:27018: connection closed (configured timeouts: connectTimeoutMS: 2000.0ms)
unit-shard-two-0: 01:52:10 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-self-signed-certificates-0: 01:52:14 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6fada3fd-9be7-47de-8804-435d7dd4dd03:r#10#config-server": settings 6fada3fd-9be7-47de-8804-435d7dd4dd03:r#10#config-server not found (not found)
unit-config-server-1: 01:52:15 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6fada3fd-9be7-47de-8804-435d7dd4dd03:r#10#self-signed-certificates": settings 6fada3fd-9be7-47de-8804-435d7dd4dd03:r#10#self-signed-certificates not found (not found)
unit-config-server-0: 01:52:15 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6fada3fd-9be7-47de-8804-435d7dd4dd03:r#10#self-signed-certificates": settings 6fada3fd-9be7-47de-8804-435d7dd4dd03:r#10#self-signed-certificates not found (not found)
unit-shard-one-0: 01:52:17 ERROR unit.shard-one/0.juju-log Unable to access primary due to: shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 6715b3d07970e345e137fc37, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-shard-one-0: 01:52:20 ERROR unit.shard-one/0.juju-log Unable to access primary due to: shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 6715b3d337968b0805a2ff2f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-0.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-0.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-1.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('shard-one-2.shard-one-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-one-2.shard-one-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-shard-two-0: 01:52:20 ERROR unit.shard-two/0.juju-log Unable to access primary due to: shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 6715b3d3ef49c8a16a44e639, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-two-0.shard-two-endpoints', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('shard-two-0.shard-two-endpoints:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-shard-one-1: 01:52:52 ERROR unit.shard-one/1.juju-log Unable to access primary due to: No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 6715b3f396666e49e6ea21b3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('shard-one-1.shard-one-endpoints', 27017) server_type: RSGhost, rtt: 0.000698197000019718>]>
controller-0: 01:54:05 ERROR juju.worker.caasapplicationprovisioner.runner exited "shard-one": finding filesystem info for shard-one-mongodb-logs-4dcb4777: unable to get persistent volume claim: k8s: persistentvolumeclaims "shard-one-mongodb-logs-4dcb4777-shard-one-1" not found
unit-config-server-1: 01:55:17 ERROR unit.config-server/1.juju-log Cannot initialize workload: MissingSecretError('No secret defined for app, keyfile')
unit-shard-one-0: 01:56:55 ERROR unit.shard-one/0.juju-log certificates:17: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-1: 01:56:55 ERROR unit.shard-one/1.juju-log certificates:17: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-two-0: 01:56:55 ERROR unit.shard-two/0.juju-log certificates:18: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-2: 01:56:56 ERROR unit.shard-one/2.juju-log certificates:17: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 01:56:56 ERROR unit.config-server/1.juju-log certificates:19: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 01:56:56 ERROR unit.shard-one/0.juju-log certificates:17: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-1: 01:56:56 ERROR unit.shard-one/1.juju-log certificates:17: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:56:56 ERROR unit.config-server/0.juju-log certificates:19: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-two-0: 01:56:56 ERROR unit.shard-two/0.juju-log certificates:18: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 01:56:56 ERROR unit.config-server/1.juju-log certificates:19: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-2: 01:56:57 ERROR unit.shard-one/2.juju-log certificates:17: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:56:57 ERROR unit.config-server/0.juju-log certificates:19: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 01:58:38 ERROR unit.config-server/0.juju-log config-server:20: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=88ffc925-aa0a-4108-a5a1-9df6776e5d3f,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=88ffc925-aa0a-4108-a5a1-9df6776e5d3f,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729475917, 1), \'signature\': {\'hash\': b\'\\xe6\\x93\\x82[\\x84o\\xe3\\xce\\x05>\\xcf\\x087\\x91\\xee\\xbaD\\x11p\\xc9\', \'keyId\': 7428041690985791513}}, \'operationTime\': Timestamp(1729475917, 1)}')
unit-config-server-0: 01:58:38 ERROR unit.config-server/0.juju-log config-server:20: Failed to add shard-one to cluster
unit-config-server-0: 01:58:38 ERROR unit.config-server/0.juju-log config-server:20: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=88ffc925-aa0a-4108-a5a1-9df6776e5d3f,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=88ffc925-aa0a-4108-a5a1-9df6776e5d3f,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729475917, 1), \'signature\': {\'hash\': b\'\\xe6\\x93\\x82[\\x84o\\xe3\\xce\\x05>\\xcf\\x087\\x91\\xee\\xbaD\\x11p\\xc9\', \'keyId\': 7428041690985791513}}, \'operationTime\': Timestamp(1729475917, 1)}')
unit-config-server-0: 01:58:55 ERROR unit.config-server/0.juju-log config-server:20: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729475935, 4), \'signature\': {\'hash\': b\'\\x93\\xe2\\x03\\xab\\xbe5\\xdb\\xbe1l\\x0cmU\\x1f\\x93\\x96\\x1cqay\', \'keyId\': 7428041690985791513}}, \'operationTime\': Timestamp(1729475935, 4)}')
unit-config-server-0: 01:58:55 ERROR unit.config-server/0.juju-log config-server:20: Failed to add shard-one to cluster
unit-config-server-0: 01:58:55 ERROR unit.config-server/0.juju-log config-server:20: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729475935, 4), \'signature\': {\'hash\': b\'\\x93\\xe2\\x03\\xab\\xbe5\\xdb\\xbe1l\\x0cmU\\x1f\\x93\\x96\\x1cqay\', \'keyId\': 7428041690985791513}}, \'operationTime\': Timestamp(1729475935, 4)}')
unit-shard-one-2: 01:59:01 ERROR unit.shard-one/2.juju-log certificates:17: An unknown certificate is available -- ignoring.
unit-shard-one-2: 01:59:01 ERROR unit.shard-one/2.juju-log certificates:17: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:59:01 ERROR unit.shard-one/1.juju-log certificates:17: An unknown certificate is available -- ignoring.
unit-shard-one-1: 01:59:02 ERROR unit.shard-one/1.juju-log certificates:17: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:59:07 ERROR unit.shard-one/0.juju-log certificates:17: An unknown certificate is available -- ignoring.
unit-shard-one-0: 01:59:07 ERROR unit.shard-one/0.juju-log certificates:17: An unknown certificate is available -- ignoring.
unit-config-server-0: 01:59:12 ERROR unit.config-server/0.juju-log config-server:20: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729475951, 1), \'signature\': {\'hash\': b\'?\\x9e\\xaa\\x1d\\x89\\x87\\xeau\\x0b]\\xd0\\xf3k\\xca6K\\xd4\\xea\\x9d\\xf9\', \'keyId\': 7428041690985791513}}, \'operationTime\': Timestamp(1729475951, 1)}')
unit-config-server-0: 01:59:12 ERROR unit.config-server/0.juju-log config-server:20: Failed to add shard-one to cluster
unit-config-server-0: 01:59:12 ERROR unit.config-server/0.juju-log config-server:20: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729475951, 1), \'signature\': {\'hash\': b\'?\\x9e\\xaa\\x1d\\x89\\x87\\xeau\\x0b]\\xd0\\xf3k\\xca6K\\xd4\\xea\\x9d\\xf9\', \'keyId\': 7428041690985791513}}, \'operationTime\': Timestamp(1729475951, 1)}')
unit-config-server-0: 01:59:34 ERROR unit.config-server/0.juju-log config-server:21: Failed to add shard shard-two to the config server, error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=88ffc925-aa0a-4108-a5a1-9df6776e5d3f,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=88ffc925-aa0a-4108-a5a1-9df6776e5d3f,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729475974, 1), \'signature\': {\'hash\': b\'\\xf2X\\xcc\\xf1i\\xff\\x13\\x96\\xc8Y\\t\\xff\\xd8\\xb8\\r\\xcf\\x8d4\\x13+\', \'keyId\': 7428041690985791513}}, \'operationTime\': Timestamp(1729475974, 1)}')
unit-config-server-0: 01:59:34 ERROR unit.config-server/0.juju-log config-server:21: Failed to add shard-two to cluster
unit-config-server-0: 01:59:35 ERROR unit.config-server/0.juju-log config-server:21: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find user "O=config-server,x500UniqueIdentifier=88ffc925-aa0a-4108-a5a1-9df6776e5d3f,CN=config-server" for db "$external", full error: {\'ok\': 0.0, \'errmsg\': \'Could not find user "O=config-server,x500UniqueIdentifier=88ffc925-aa0a-4108-a5a1-9df6776e5d3f,CN=config-server" for db "$external"\', \'code\': 11, \'codeName\': \'UserNotFound\', \'$clusterTime\': {\'clusterTime\': Timestamp(1729475974, 1), \'signature\': {\'hash\': b\'\\xf2X\\xcc\\xf1i\\xff\\x13\\x96\\xc8Y\\t\\xff\\xd8\\xb8\\r\\xcf\\x8d4\\x13+\', \'keyId\': 7428041690985791513}}, \'operationTime\': Timestamp(1729475974, 1)}')
unit-shard-two-0: 01:59:51 ERROR unit.shard-two/0.juju-log certificates:18: An unknown certificate is available -- ignoring.
unit-shard-two-0: 01:59:51 ERROR unit.shard-two/0.juju-log certificates:18: An unknown certificate is available -- ignoring.
unit-shard-one-1: 02:07:07 ERROR unit.shard-one/1.juju-log certificates:22: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-1: 02:07:07 ERROR unit.shard-one/1.juju-log certificates:22: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-2: 02:08:21 ERROR unit.shard-one/2.juju-log certificates:22: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-2: 02:08:22 ERROR unit.shard-one/2.juju-log certificates:22: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-shard-one-0: 02:11:36 ERROR unit.shard-one/0.juju-log certificates:22: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-shard-one-0: 02:11:37 ERROR unit.shard-one/0.juju-log certificates:22: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 02:12:27 ERROR unit.config-server/1.juju-log certificates:19: This operation (delete_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:12:27 ERROR unit.config-server/1.juju-log certificates:19: This operation (delete_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:14:27 ERROR unit.config-server/1.juju-log certificates:23: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-1: 02:14:28 ERROR unit.config-server/1.juju-log certificates:23: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-0: 02:14:28 ERROR unit.config-server/0.juju-log certificates:23: Non-existing secret unit:int-cert-secret was attempted to be removed.
unit-config-server-0: 02:14:29 ERROR unit.config-server/0.juju-log certificates:23: Non-existing secret unit:ext-cert-secret was attempted to be removed.
unit-config-server-1: 02:14:33 ERROR unit.config-server/1.juju-log certificates:23: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:14:33 ERROR unit.config-server/1.juju-log certificates:23: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:14:47 ERROR unit.config-server/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:14:47 ERROR unit.config-server/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:15:01 ERROR unit.config-server/1.juju-log certificates:23: This operation (update_relation_data()) can only be performed by the leader unit
unit-config-server-1: 02:15:01 ERROR unit.config-server/1.juju-log certificates:23: This operation (update_relation_data()) can only be performed by the leader unit
unit-shard-one-2: 02:16:38 ERROR unit.shard-one/2.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.
unit-shard-one-1: 02:16:39 ERROR unit.shard-one/1.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.
unit-shard-one-0: 02:16:47 ERROR unit.shard-one/0.juju-log Shard is integrated to a different CA than the config server. Please use the same CA for all cluster components.

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...