[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  application/0 [idle] active: received database credentials of the second database
  application/1 [idle] active: received database credentials of the second database
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] active: 
  another-database/0 [idle] active: Primary
  another-database/1 [idle] active: 
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] active: 
[32mINFO    [0m integration.helpers:helpers.py:206 Running mongo command: 'mongosh --quiet --eval \'db.runCommand({ replSetGetStatus : 1 });\' "mongodb://relation-2:YMlNU6iLFapRk84cekwQrRJhjc3c61nd@mongodb-k8s-1.mongodb-k8s-endpoints:27017,mongodb-k8s-0.mongodb-k8s-endpoints:27017/application_first_database?replicaSet=mongodb-k8s&authSource=admin"'
[32mINFO    [0m integration.helpers:helpers.py:448 Checking or creating helper mongo pod ...
[32mINFO    [0m integration.helpers:helpers.py:453 pod 'mongodb-helper' in namespace 'test' already exists.
[32mINFO    [0m integration.helpers:helpers.py:492 Checking pod mongodb-helper is ready...
[1m[31mERROR   [0m integration.helpers:helpers.py:234 code 1; stdout ''; stderr: 'MongoServerError: Authentication failed.\ncommand terminated with exit code 1\n'
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:47:08Z

App                  Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
another-application           active      1  application             1  10.152.183.221  no       received database credentials of the first database
another-database              active      2  mongodb-k8s             1  10.152.183.132  no       Primary
application                   active      2  application             0  10.152.183.153  no       received database credentials of the second database
mongodb-k8s                   active      2  mongodb-k8s             0  10.152.183.147  no       Primary

Unit                    Workload  Agent  Address      Ports  Message
another-application/0*  active    idle   10.1.217.29         received database credentials of the first database
another-database/0*     active    idle   10.1.217.20         Primary
another-database/1      active    idle   10.1.217.21         
application/0*          active    idle   10.1.217.14         received database credentials of the second database
application/1           active    idle   10.1.217.15         received database credentials of the second database
mongodb-k8s/0*          active    idle   10.1.217.12         Primary
mongodb-k8s/1           active    idle   10.1.217.13         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-mongodb-k8s-3: 01:41:36 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 67048dcf83930d3dfda3f741, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0005177040000035049>]>
unit-mongodb-k8s-2: 01:42:34 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 67048e09acc24bc63c7f3f5e, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0014480709999133978>]>

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...