[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 2 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/1 [executing] maintenance: installing charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 1 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/2 [executing] terminated: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 1 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 2 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 2 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 3 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [executing] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 3 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 4 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/2 [executing] active: 
  mongodb-k8s/1 [executing] active: 
  mongodb-k8s/3 [executing] active: 
  mongodb-k8s/4 [executing] maintenance: installing charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 4 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] maintenance: stopping charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 5 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] error: hook failed: "secret-changed"
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 5 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
  mongodb-k8s/5 [executing] terminated: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 6 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [idle] error: hook failed: "secret-changed"
  mongodb-k8s/5 [executing] maintenance: installing charm software
  mongodb-k8s/6 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [executing] active: 
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 6 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
  mongodb-k8s/5 [executing] terminated: 
  mongodb-k8s/6 [executing] maintenance: stopping charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 7 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [executing] maintenance: installing charm software
  mongodb-k8s/6 [executing] maintenance: installing charm software
  mongodb-k8s/7 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/2 [executing] active: 
  mongodb-k8s/1 [executing] active: 
  mongodb-k8s/3 [executing] active: 
  mongodb-k8s/4 [executing] active: 
  mongodb-k8s/5 [executing] active: 
  mongodb-k8s/6 [executing] active: 
  mongodb-k8s/7 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 7 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
  mongodb-k8s/7 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
  mongodb-k8s/5 [executing] terminated: 
  mongodb-k8s/6 [executing] terminated: 
  mongodb-k8s/7 [executing] maintenance: stopping charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:51:05Z

App          Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
mongodb-k8s           active      1  mongodb-k8s             0  10.152.183.132  no       Primary

Unit            Workload  Agent  Address      Ports  Message
mongodb-k8s/0*  active    idle   10.1.79.138         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-mongodb-k8s-2: 01:36:49 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e245b089e1123f0b35751d, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0005622030000154155>]>
unit-mongodb-k8s-1: 01:37:16 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e245cb90839f71066410f0, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.00043374199998424956>]>
unit-mongodb-k8s-1: 01:38:25 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e24610e33a8c12ae9cc5ec, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0005343999999922744>]>
unit-mongodb-k8s-1: 01:39:55 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e2466a6c9b2c18483c466f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0011811109999371183>]>
unit-mongodb-k8s-2: 01:39:56 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e2466be91d09a484900078, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0008794660000148724>]>
unit-mongodb-k8s-3: 01:40:00 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e2466f48cb0974c2dbaf1d, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0005973289999019471>]>
unit-mongodb-k8s-2: 01:41:43 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e246d6a9e05dc9ec0310f5, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0020736809999561956>]>
unit-mongodb-k8s-1: 01:41:43 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e246d69e814bed39f069ee, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.00421008000000711>]>
unit-mongodb-k8s-4: 01:41:50 ERROR unit.mongodb-k8s/4.juju-log mongodb-k8s/4.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e246ddfab8ea2f6c95299c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-4.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0006136490000017147>]>
unit-mongodb-k8s-4: 01:42:35 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 563, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:42:35Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:42:35.607Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:42:35.608Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-12T01:42:35Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:42:35 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:42:35 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-4: 01:42:37 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 563, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:42:37Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:42:37.545Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:42:37.545Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-12T01:42:37Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:42:37 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:42:37 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-4: 01:42:40 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 868, in _on_secret_changed
    self._connect_mongodb_exporter()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1362, in _connect_mongodb_exporter
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:42:39Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:42:39.972Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:42:39.972Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-12T01:42:39Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:42:40 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:43:41 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 869, in _on_secret_changed
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1398, in _connect_pbm_agent
    for attempt in Retrying(
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1404, in _connect_pbm_agent
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:43:41Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:43:41.822Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:43:41.822Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-12T01:43:41Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:43:42 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:43:54 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 563, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:43:54Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:43:54.217Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:43:54.218Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-12T01:43:54Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:43:54 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:43:54 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-4: 01:43:55 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 563, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:43:55Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:43:55.965Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:43:55.966Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-12T01:43:55Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:43:56 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:43:56 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-2: 01:44:39 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e24786ad661632249e3f2b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.010403332000009868>]>
unit-mongodb-k8s-1: 01:44:39 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e24786d83fa6544c19b4d5, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0007907870000281036>]>
unit-mongodb-k8s-4: 01:45:38 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 563, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:45:38Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:45:38.406Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:45:38.406Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-12T01:45:38Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:45:38 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:45:38 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-4: 01:45:40 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 563, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:45:40Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:45:40.656Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:45:40.656Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-12T01:45:40Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:45:41 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:45:41 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-4: 01:45:43 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 868, in _on_secret_changed
    self._connect_mongodb_exporter()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1362, in _connect_mongodb_exporter
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:45:43Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:45:43.906Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:45:43.907Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-12T01:45:43Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:45:44 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:46:45 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 869, in _on_secret_changed
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1398, in _connect_pbm_agent
    for attempt in Retrying(
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1404, in _connect_pbm_agent
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:46:45Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:46:45.939Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:46:45.939Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-12T01:46:45Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:46:46 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:46:58 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 563, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:46:58Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:46:58.547Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:46:58.547Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-09-12T01:46:58Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:46:58 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:46:58 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-4: 01:47:00 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1615, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 563, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2278, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2131, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2228, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-09-12T01:47:00Z INFO Most recent service output:
    {"t":{"$date":"2024-09-12T01:47:00.291Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-09-12T01:47:00.292Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-09-12T01:47:00Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:47:00 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:47:00 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-2: 01:47:51 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e24846bda4001f9a3a0a6f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.006217815999889353>]>
unit-mongodb-k8s-1: 01:47:51 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e24846e6ac021baddd5ea8, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0018842099998437334>]>
unit-mongodb-k8s-3: 01:47:52 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e24847ede317ded99b7596, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0008990220001123816>]>
unit-mongodb-k8s-5: 01:48:01 ERROR unit.mongodb-k8s/5.juju-log mongodb-k8s/5.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e248507c9a7dd140973e06, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-5.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.01072913799998787>]>
unit-mongodb-k8s-1: 01:50:22 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e248dd21ae7de43bbe4a9a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.03129092600011063>]>
unit-mongodb-k8s-2: 01:50:23 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e248debf241c885929c07b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.001071635000016613>]>
unit-mongodb-k8s-4: 01:50:26 ERROR unit.mongodb-k8s/4.juju-log mongodb-k8s/4.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66e248e1e0a0585aa50cfbc8, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-4.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0009454690000438859>]>

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...