[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 2 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 1 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 1 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 2 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 2 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 3 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [executing] maintenance: installing charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 3 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 4 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] active: 
  mongodb-k8s/2 [executing] active: 
  mongodb-k8s/3 [executing] active: 
  mongodb-k8s/4 [executing] maintenance: installing charm software
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 4 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 5 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 5 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 6 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [executing] maintenance: installing charm software
  mongodb-k8s/6 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [executing] maintenance: installing charm software
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] error: hook failed: "secret-changed"
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 6 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
  mongodb-k8s/5 [executing] terminated: 
  mongodb-k8s/6 [executing] terminated: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:72 Scaling up by 7 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] maintenance: installing charm software
  mongodb-k8s/2 [executing] maintenance: installing charm software
  mongodb-k8s/3 [executing] maintenance: installing charm software
  mongodb-k8s/4 [executing] maintenance: installing charm software
  mongodb-k8s/5 [executing] maintenance: installing charm software
  mongodb-k8s/6 [executing] maintenance: installing charm software
  mongodb-k8s/7 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] active: 
  mongodb-k8s/2 [executing] active: 
  mongodb-k8s/3 [executing] active: 
  mongodb-k8s/4 [executing] active: 
  mongodb-k8s/5 [executing] active: 
  mongodb-k8s/6 [executing] active: 
  mongodb-k8s/7 [executing] active: 
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m integration.test_teardown:test_teardown.py:74 Scaling down by 7 units
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
  mongodb-k8s/1 [idle] active: 
  mongodb-k8s/2 [idle] active: 
  mongodb-k8s/3 [idle] active: 
  mongodb-k8s/4 [idle] active: 
  mongodb-k8s/5 [idle] active: 
  mongodb-k8s/6 [idle] active: 
  mongodb-k8s/7 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [executing] active: Primary
  mongodb-k8s/1 [executing] terminated: 
  mongodb-k8s/2 [executing] terminated: 
  mongodb-k8s/3 [executing] terminated: 
  mongodb-k8s/4 [executing] terminated: 
  mongodb-k8s/5 [executing] terminated: 
  mongodb-k8s/6 [executing] maintenance: stopping charm software
  mongodb-k8s/7 [executing] maintenance: stopping charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongodb-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:340 Unit name: mongodb-k8s/0. Target unit name: mongodb-k8s/0, True
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  01:49:07Z

App          Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
mongodb-k8s           active      1  mongodb-k8s             0  10.152.183.138  no       Primary

Unit            Workload  Agent  Address     Ports  Message
mongodb-k8s/0*  active    idle   10.1.6.138         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-mongodb-k8s-2: 01:35:01 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd0443dcdb9b25c59fd6a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0004968659999917691>]>
unit-mongodb-k8s-1: 01:35:26 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd05d72d4bc50fdeafb7e, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0004593940000177099>]>
unit-mongodb-k8s-2: 01:35:55 ERROR unit.mongodb-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:35:55Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:35:55.664Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:35:55.664Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-08-29T01:35:55Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-1: 01:35:55 ERROR unit.mongodb-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:35:55Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:35:55.697Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:35:55.697Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-08-29T01:35:55Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-2: 01:35:55 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-2: 01:35:55 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-1: 01:35:55 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-1: 01:35:55 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-2: 01:35:57 ERROR unit.mongodb-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 863, in _on_secret_changed
    self._connect_mongodb_exporter()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1355, in _connect_mongodb_exporter
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:35:57Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:35:57.366Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:35:57.366Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-08-29T01:35:57Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-1: 01:35:57 ERROR unit.mongodb-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 863, in _on_secret_changed
    self._connect_mongodb_exporter()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 1355, in _connect_mongodb_exporter
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:35:57Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:35:57.394Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:35:57.394Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-08-29T01:35:57Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-2: 01:35:57 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-1: 01:35:57 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-2: 01:36:58 ERROR unit.mongodb-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 864, in _on_secret_changed
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1391, in _connect_pbm_agent
    for attempt in Retrying(
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 1397, in _connect_pbm_agent
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:36:58Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:36:58.424Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:36:58.424Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-08-29T01:36:58Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-1: 01:36:58 ERROR unit.mongodb-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 864, in _on_secret_changed
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 1391, in _connect_pbm_agent
    for attempt in Retrying(
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/./src/charm.py", line 1397, in _connect_pbm_agent
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-1/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:36:58Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:36:58.442Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:36:58.442Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-08-29T01:36:58Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-2: 01:36:58 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-1: 01:36:58 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-1: 01:37:44 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd0e7db258d67090a1efa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0009966080000367583>]>
unit-mongodb-k8s-1: 01:39:12 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd13ee86bb6d243cf79d4, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.002422177999960695>]>
unit-mongodb-k8s-3: 01:39:16 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd1432bca35aecb35875c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0010398240000313308>]>
unit-mongodb-k8s-1: 01:40:55 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd1a6d9b2ceab4a58f36d, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0007810199999767065>]>
unit-mongodb-k8s-2: 01:40:55 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd1a60321eb99adb0c40c, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.001297450000038225>]>
unit-mongodb-k8s-3: 01:40:59 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd1aa6b446e478e9b78d7, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.003454206000014892>]>
unit-mongodb-k8s-4: 01:41:44 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:41:44Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:41:44.662Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:41:44.662Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-08-29T01:41:44Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:41:44 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:41:44 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-2: 01:42:45 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd21485acb184f4f78104, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0037523500000133936>]>
unit-mongodb-k8s-1: 01:42:45 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd21461457603fdbaadc1, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0017001710000386083>]>
unit-mongodb-k8s-3: 01:42:47 ERROR unit.mongodb-k8s/3.juju-log mongodb-k8s/3.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd21611d1651f916cecd4, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-3.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0004231190000609786>]>
unit-mongodb-k8s-5: 01:42:54 ERROR unit.mongodb-k8s/5.juju-log mongodb-k8s/5.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd21d8eff698502a82bd9, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-5.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.001759852999953182>]>
unit-mongodb-k8s-5: 01:43:40 ERROR unit.mongodb-k8s/5.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:43:40Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:43:40.358Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:43:40.359Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-08-29T01:43:40Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-5: 01:43:40 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-5: 01:43:40 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-4: 01:43:41 ERROR unit.mongodb-k8s/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-4/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:43:41Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:43:41.193Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:43:41.193Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-08-29T01:43:41Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-4: 01:43:41 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-4: 01:43:41 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-5: 01:43:42 ERROR unit.mongodb-k8s/5.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/./src/charm.py", line 863, in _on_secret_changed
    self._connect_mongodb_exporter()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/./src/charm.py", line 1355, in _connect_mongodb_exporter
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:43:42Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:43:42.218Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:43:42.218Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-08-29T01:43:42Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-5: 01:43:42 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-5: 01:44:44 ERROR unit.mongodb-k8s/5.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/./src/charm.py", line 864, in _on_secret_changed
    self._connect_pbm_agent()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/./src/charm.py", line 1391, in _connect_pbm_agent
    for attempt in Retrying(
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/./src/charm.py", line 1397, in _connect_pbm_agent
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-5/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:44:44Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:44:44.215Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:44:44.215Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"Could not open a file for writing at the given auditPath: /var/log/mongodb/audit.log"}}}
2024-08-29T01:44:44Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-5: 01:44:44 ERROR juju.worker.uniter.operation hook "secret-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-2: 01:45:56 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd2d3d3a6577924f87dd7, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.012720089000140433>]>
unit-mongodb-k8s-1: 01:45:57 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd2d4bc4c770cc81bd174, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0008071149998158944>]>
unit-mongodb-k8s-4: 01:46:01 ERROR unit.mongodb-k8s/4.juju-log mongodb-k8s/4.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd2d886ab0602f815d276, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-4.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0005044080000971007>]>
unit-mongodb-k8s-5: 01:46:05 ERROR unit.mongodb-k8s/5.juju-log mongodb-k8s/5.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd2dcc5626c27855c81e3, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-5.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.000467362000108551>]>
unit-mongodb-k8s-3: 01:46:58 ERROR unit.mongodb-k8s/3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 1608, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/./src/charm.py", line 558, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mongodb-k8s-3/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-29T01:46:58Z INFO Most recent service output:
    {"t":{"$date":"2024-08-29T01:46:58.754Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-29T01:46:58.754Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-08-29T01:46:58Z ERROR cannot start service: exited quickly with code 1
-----
unit-mongodb-k8s-3: 01:46:59 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-3: 01:46:59 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed
unit-mongodb-k8s-2: 01:48:23 ERROR unit.mongodb-k8s/2.juju-log mongodb-k8s/2.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd3665fbb4dc4420ae723, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-2.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0006853869999758899>]>
unit-mongodb-k8s-1: 01:48:23 ERROR unit.mongodb-k8s/1.juju-log mongodb-k8s/1.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd366fac71488005598bd, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-1.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0018048179999823333>]>
unit-mongodb-k8s-7: 01:48:39 ERROR unit.mongodb-k8s/7.juju-log mongodb-k8s/7.is_unit_in_replica_set PyMongoError=No replica set members match selector "Primary()", Timeout: 1.0s, Topology Description: <TopologyDescription id: 66cfd3763756e26490fd9d1f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongodb-k8s-7.mongodb-k8s-endpoints', 27017) server_type: RSGhost, rtt: 0.0074306850001448765>]>

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...